[versions]
asm = "9.9.1"
junit-jupiter = "5.14.2"
junit-platform = "1.14.2"
assertj = "3.27.7"
spotless = "8.2.1"
spotbugs = "6.4.8"
spotbugs-annotations = "4.9.8"
axion-release = "1.21.1"
nexus-publish = "2.0.0"
jmh-plugin = "0.7.3"

[libraries]
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
spotbugs = { module = "com.github.spotbugs.snom:spotbugs-gradle-plugin", version.ref = "spotbugs" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs-annotations" }
axion-release = { module = "pl.allegro.tech.build.axion-release:pl.allegro.tech.build.axion-release.gradle.plugin", version.ref = "axion-release" }
nexus-publish = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexus-publish" }
jmh-plugin = { module = "me.champeau.jmh:me.champeau.jmh.gradle.plugin", version.ref = "jmh-plugin" }
